# Generated by Django 4.2.3 on 2024-11-14 01:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_educationrecord_date_started_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='family',
            name='family_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
